"""empty message

Revision ID: 01d05384a3e1
Revises: a2b48acfb5e5
Create Date: 2025-04-30 17:02:54.689166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d05384a3e1'
down_revision = 'a2b48acfb5e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ensaladas')
    op.drop_table('cacahuetes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cacahuetes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cacahuetes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cacahuetes_pkey'),
    sa.UniqueConstraint('email', name='cacahuetes_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ensaladas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('biografia', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('foto_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cacahuete_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cacahuete_id'], ['cacahuetes.id'], name='ensaladas_cacahuete_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ensaladas_pkey'),
    sa.UniqueConstraint('cacahuete_id', name='ensaladas_cacahuete_id_key')
    )
    # ### end Alembic commands ###
