"""empty message

Revision ID: 09bde76f01b7
Revises: cc1640b06c0e
Create Date: 2025-04-28 09:23:58.736581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09bde76f01b7'
down_revision = 'cc1640b06c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehiculo_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['vehiculo_id'])
        batch_op.create_foreign_key(None, 'vehiculos', ['vehiculo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('vehiculo_id')

    # ### end Alembic commands ###
