"""empty message

Revision ID: 5cc89fcd86b8
Revises: 7846a8bd0632
Create Date: 2025-04-28 09:37:59.926658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc89fcd86b8'
down_revision = '7846a8bd0632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cacahuetes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('perfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biografia', sa.String(length=200), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('cacahuete_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cacahuete_id'], ['cacahuetes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cacahuete_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfiles')
    op.drop_table('cacahuetes')
    # ### end Alembic commands ###
