"""empty message

Revision ID: a2b48acfb5e5
Revises: 5cc89fcd86b8
Create Date: 2025-04-28 09:43:16.381553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b48acfb5e5'
down_revision = '5cc89fcd86b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensaladas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biografia', sa.String(length=200), nullable=False),
    sa.Column('foto_url', sa.String(length=255), nullable=False),
    sa.Column('cacahuete_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cacahuete_id'], ['cacahuetes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cacahuete_id')
    )
    op.drop_table('perfiles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('biografia', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('foto_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cacahuete_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cacahuete_id'], ['cacahuetes.id'], name='perfiles_cacahuete_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='perfiles_pkey'),
    sa.UniqueConstraint('cacahuete_id', name='perfiles_cacahuete_id_key')
    )
    op.drop_table('ensaladas')
    # ### end Alembic commands ###
