"""empty message

Revision ID: ab1010095820
Revises: 09bde76f01b7
Create Date: 2025-04-28 09:27:48.739313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1010095820'
down_revision = '09bde76f01b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.drop_constraint('vehiculos_personaje_id_fkey', type_='foreignkey')
        batch_op.drop_column('personaje_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personaje_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('vehiculos_personaje_id_fkey', 'personajes', ['personaje_id'], ['id'])

    # ### end Alembic commands ###
