"""empty message

Revision ID: c06a844cacde
Revises: c1f1f230d872
Create Date: 2025-04-25 19:24:48.282740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06a844cacde'
down_revision = 'c1f1f230d872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.drop_constraint('personajes_vehiculo_id_key', type_='unique')

    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.drop_constraint('vehiculos_personaje_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.create_unique_constraint('vehiculos_personaje_id_key', ['personaje_id'])

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.create_unique_constraint('personajes_vehiculo_id_key', ['vehiculo_id'])

    # ### end Alembic commands ###
