"""empty message

Revision ID: c1f1f230d872
Revises: e45f9356e887
Create Date: 2025-04-25 18:47:29.013958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f1f230d872'
down_revision = 'e45f9356e887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehiculo_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['vehiculo_id'])
        batch_op.create_foreign_key(None, 'vehiculos', ['vehiculo_id'], ['id'])

    with op.batch_alter_table('personajes_favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_agregado', sa.DateTime(), nullable=False))

    with op.batch_alter_table('planetas_favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_agregado', sa.DateTime(), nullable=False))

    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personaje_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['personaje_id'])
        batch_op.create_foreign_key(None, 'personajes', ['personaje_id'], ['id'])

    with op.batch_alter_table('vehiculos_favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_agregado', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos_favoritos', schema=None) as batch_op:
        batch_op.drop_column('fecha_agregado')

    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('personaje_id')

    with op.batch_alter_table('planetas_favoritos', schema=None) as batch_op:
        batch_op.drop_column('fecha_agregado')

    with op.batch_alter_table('personajes_favoritos', schema=None) as batch_op:
        batch_op.drop_column('fecha_agregado')

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('vehiculo_id')

    # ### end Alembic commands ###
