"""empty message

Revision ID: cc1640b06c0e
Revises: c06a844cacde
Create Date: 2025-04-28 09:19:10.161562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1640b06c0e'
down_revision = 'c06a844cacde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.drop_constraint('personajes_vehiculo_id_fkey', type_='foreignkey')
        batch_op.drop_column('vehiculo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehiculo_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('personajes_vehiculo_id_fkey', 'vehiculos', ['vehiculo_id'], ['id'])

    # ### end Alembic commands ###
